plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-core:2.15.2'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.15.2'
    implementation 'org.xerial:sqlite-jdbc:3.42.0.0'
}

sourceSets {
    main {
        java {
            srcDirs = ['lib']
        }
    }
}

jar {
    archiveFileName = 'SeqDB.jar'
    destinationDirectory = file('lib')

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    
    manifest {
        attributes(
            'Implementation-Title': 'SeqDB',
            'Implementation-Version': '1.0'
        )
    }
}

clean {
    delete fileTree('lib') {
        include '*.jar'
    }
}
