name: Nextflow linting

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - subworkflows/**
      - modules/**
      - main.nf
      - .github/workflows/nf-lint.yml
  pull_request:
    branches: [ main ]
    paths:
      - subworkflows/**
      - modules/**
      - main.nf
      - .github/workflows/nf-lint.yml

concurrency:
  group: nf-lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run NF linter
        run: |
          set -euo pipefail
          docker run --rm --entrypoint="" \
            -v "${PWD}:/data" \
            public.ecr.aws/aws-genomics/linter-rules-for-nextflow:v0.1.2 \
            ./check.sh --fail-on-violations general
