name: Unit Tests

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/unit-tests.yml
      - bin/**
      - conf/**
      - lib/**
      - modules/**
      - subworkflows/**
      - tests/**
      - main.nf
      - nextflow.config

  pull_request:
    branches: [ main ]
    paths:
      - lib/**
      - modules/**
      - subworkflows/**
      - tests/**
      - workflows/**
      - nextflow.config
      - main.nf
      - .github/workflows/unit-tests.yml

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: '25.04.6'

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash -s 0.9.3
          sudo mv nf-test /usr/local/bin/

      - name: Run NF-Test unit tests
        run: nf-test test tests/unit_tests
